### ISSUE TITLE
Readme is outdated

### ISSUE THREAD

**Issue by GoldenEpsilon** [elendiastarman/Tametsi-level-generator#1]
I have a friend who just finished tametsi that is interested in using the generator, but we can't figure out how to use it - I've gotten it to start generating rounds infinitely, but I can't figure out where it turns into an actual level. 

Any help would be greatly appreciated. Thanks!

**Comment by elendiastarman** [comment]
Sorry it took me so long to get around to actually doing this. I blame life. >_>

If you still find anything confusing, please let me know here or in a new issue and I'll try to address it sooner than 1.5 years later! :)
